#pragma once

#define MASTER_RIGHT

// pimoroni zone
#define PIMORONI_TRACKBALL_ENABLE
#define PIMORONI_TRACKBALL_ROTATE
#define POINTING_DEVICE_TASK_THROTTLE_MS 8

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 2000

#define COMBO_TERM_PER_COMBO
#define COMBO_PROCESS_KEY_RELEASE
#define COMBO_HOLD_TERM 140

#define TAPPING_TOGGLE 2

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64
